#!/bin/bash

command=$1
input_dir=$(dirname $command)/input
output_dir=$(dirname $command)/output


for input_file in `ls $input_dir/*.txt`; do
    filename=$(basename $input_file)
    tmpfilename=${TMP:-/tmp}/$filename.diff

    if diff -u <($command < $input_file) $output_dir/$filename > $tmpfilename; then
        printf "\e[32mcheck $filename: OK!\e[m\n"
    else
        printf "\e[31mcheck $filename: NG\e[m\n"
        cat $tmpfilename
    fi
    echo -e "-----\n"
done
