[package]
name = "chap10-3"
version = "0.1.0"
authors = ["Fumitaka Tokumitsu <toku345@gmail.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
